name: Test Commit

on:

  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: "write"
  contents: "read"

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          firstParent: true