name: Job Deployment

on:
  push:
    branches: [ prod ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: ecs/**
        
      - name: List all changed files
        run: |
          files=()
          for file in "${{ steps.changed-files.outputs.all_changed_files }}"; do
            echo $file is changed
            files+=($file)
          done
          echo $files[@]